[mypy]
python_version = 3.11
strict = True
exclude = (?x)(
    (^|[\\/])(\..*|__.*__|build|dist|venv|env|node_modules|.*\.egg-info|intelag_vsix_packages|intelag_vsix_creator|common_media|script|intelag_packages|intelag_data_collection_manager)[\\/]
    |(^|[\\/])(\.mypy_cache|\.ruff_cache|\.pytest_cache|\.tox)[\\/]?
    )

warn_return_any = True
warn_unused_configs = True
show_error_codes = True
pretty = True
explicit_package_bases = True
namespace_packages = True
mypy_path = .
# Per-module overrides for untyped third-party libraries

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-rich.*]
ignore_missing_imports = True
